console.log(typeof 'hassan')
console.log(typeof true)
console.log(typeof undefined)
console.log(typeof null)
console.log(firstName)
console.log(lastName)
console.log(maritalStatus)
console.log(country)
console.log(age)
console.log(firstName0, lastName0, maritalStatus0, country0, age0)
console.log('I am', myAge, 'years old.')
console.log('You are', yourAge, 'years old.')